Say you work in an e-commerce company as a Data Scientist for the Category Management group specifically Mobile Phone Accessories.

Your objective is to derive insights from the sales transaction data to help your team maximize the sales.

What tools and techniques will you leverage to get this done ?

**Approaching Pattern Mining**

You can approach this problem in multiple ways.

First, you can identify a list of sale transactions and see what are the most sold accessories.

Based on that you can narrow down and see what are the accessories that go along with the most sold accessory.

You can create your rules and generalize the model based on the strength and confidence of the data.

**Insights**

From your analysis you have identified that customers who have purchased Mobile Adapters and Bluetooth Headsets are more likely to buy a Charger.

You can inform your team to bundle adapters and chargers offering them a combo price

You can perform similar analysis on different transactions and come up with rules based on the frequency of items purchased.

# Intro

**Frequency of Frequent Items**

You have a list of sales transactions that happened over the last 1 hour
The goal is to determine patterns in the items purchased
You want to develop an association rule among the items ... How will you do that ?

**Approach**

To reach the end goal , the first step taken is to determine the support for a given set of items. For Example , you see Bread and Butter in 60% of the transactions. Is that considered frequent ? What if the frequency was 20% or 80 % ?

**Support**

Support is the number of times you see an item or items over a list of all the transactions.
Representing Support

Support of two items A and B is represented as
support(A->B) = P(AUB)

The support of A -> B is the percentage of transactions that contain both A and B.

- A could be Mobile Chargers
- B could be Adapters

Support of A -> B = Number of Transactions that have both A and B / Total Number of Transactions

**EXAMPLE**

Consider the below set of transaction

basket1 = {'vanilla wafers', 'bananas' , 'dog food'}

basket2 = {'bananas', 'bread', 'yogurt'}

basket3 = {'bananas','apples','yogurt'}

basket4 = {'vanilla wafers','bananas','whipped cream'}

basket5 = {'bread', 'vanilla wafers' , 'yogurt'}

basket6 = {'milk' 'bread' 'bananas'}

basket7 = {'vanilla wafers', 'apples' , 'bananas'}

basket8 = {'yogurt', 'apples', 'vanilla wafers'}

basket9 = {'vanilla wafers', 'bananas' , 'milk'}

basket10 =  {'bananas', 'bread', 'peanut butter'}

If we calculate the support for each item we will get

apples 3
bananas 8
bread 4
dog food 1
milk 2
peanut butter 1
vanilla wafers 6
yogurt 4
whipped cream 1

When the number expressed above is divided by total number of transactions , we get the percentage value.

**CONFIDENCE**

In the previous steps , you have understood how to identify all the frequent items in your baskets.
After identifying them , the next logical step is to see if one of the items is triggering purchase of another item


Consider the below transaction set.

basket1 = {'vanilla wafers', 'bananas' , 'dog food'}

basket2 = {'bananas', 'bread', 'yogurt'}

basket3 = {'bananas','apples','yogurt'}

basket4 = {'vanilla wafers','bananas','whipped cream'}

basket5 = {'bread', 'vanilla wafers' , 'yogurt'}

basket6 = {'milk' 'bread' 'bananas'}

basket7 = {'vanilla wafers', 'apples' , 'bananas'}

basket8 = {'yogurt', 'apples', 'vanilla wafers'}

basket9 = {'vanilla wafers', 'bananas' , 'milk'}

basket10 =  {'bananas', 'bread', 'peanut butter'}

From the previous example, you can see that 75% of the customers who have vanilla wafers in their cart / basket also have bananas.
On the contrary only 1% of the customers who bought bananas also bought vanilla wafers.
So, what can be inferred from this insight?

**Confidence** is a directional relationship between two or more items.

It is represented in the following manner

confidence(A->B) = P(B|A)

We can read this as the confidence of item A leading to item B is the probability of B given A.
Another way of writing confidence is

confidence(A->B) = support(AUB) / support(A)

The confidence of A->B can be explained as percentage of baskets containing A and B divided by the percentage of baskets that containing just A.

confidence(vanilla wafers->bananas) = support(vanilla wafers U bananas) / support(vanilla wafers)

= 4/6 = 67%

confidence(bananas -> vanilla wafers) = support (vanilla wafers U bananas) / support(bananas)

= 4/8 = 50%

**Lift of a Rule**

Consider the following Scenario

0.1% of all the transactions have milk and bread i.e support of milk -> bread is 0.1%

0.9% of all transactions that have milk and bread also have a banana i.e confidence of milk , bread -> banana is 0.9%

3% of all transactions involve banana alone

Is there a way to quantify how likely a customer will buy banana given that he has milk and bread in his shopping cart ?

**Lift Calculation**

Lift is a way of quantifying the support and confidence of a set of items.

Lift (x->y) = Proportion of transactions with X and Y / (proportion of transactions with x) * (prop of transactions with y)

From the problem in the previous card

X represent Milk and Bread

Y represents Banana

Lift (Milk , Bread) -> Banana = 0.9% / (0.1% * 3%) = 3

What does 3 signify ?

**Lift Significance**

In the above problem 3 signifies the following

A customer is 3 times more likely to purchase a banana given that he/she buys milk and bread together.

This number is not valid if each of the items is purchased individually.

Getting the support and confidence are the pre-requisites for Association Rule.

After getting the metrics , we can form the Association Rule.

vanilla wafers -> bananas, whipped cream
[support=10%, confidence=80%]

Interpreting the above rule , 10% of the carts or baskets have vanilla wafers , banana and whipped cream together.

80% of the customers who brought vanilla wafers also purchased bananas and whipped cream

Let us take the rule

item A -> item B , item C 
support 10 % , confidence 60% 
Left-hand side is called antecedent

Right-hand side is called consequent

Items A , B and C are purchased in 10% of the transactions

Among all the transactions that have item A , 60% of the transactions have items B and C.

**Upward Closure Property**

The property states that a given itemset can be considered frequent if all the items in the itemset are also frequent

Another way of describing this is

- There is not much value in calculating the support of any itemset if the all the itemsets are not frequent
- This property will help us find frequent item sets faster

**Finding Frequent Itemset**

The following algorithm can be implemented

- First identify and set a threshold for support
- Construct a list of singletons (1 item-set) - To get this list first start with a list that has every possible item CandidateSingletonList - Get the support value for each item - Keep only those items whose support is greater than the threshold Singleton


Repeat similar steps for 2 item and 3 item sets. This concept will be explained in detail in the successive topics.

# Implementation

In [1]:
dataset = [
    ['vanilla wafers', 'bananas' , 'dog food'],
    ['bananas', 'bread', 'yogurt'],
    ['bananas','apples','yogurt'],
    ['vanilla wafers','bananas','whipped cream'],
    ['bread', 'vanilla wafers' , 'yogurt'],
    ['milk', 'bread', 'bananas'],
    ['vanilla wafers', 'apples' , 'bananas'],
    ['yogurt', 'apples', 'vanilla wafers'],
    
]

mlxtend package can be used for implementing Association Rule Mining

frequent_patterns is the actual library

apriori , association_rules and TransactionEncoder are used

In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,apples,bananas,bread,dog food,milk,vanilla wafers,whipped cream,yogurt
0,False,True,False,True,False,True,False,False
1,False,True,True,False,False,False,False,True
2,True,True,False,False,False,False,False,True
3,False,True,False,False,False,True,True,False
4,False,False,True,False,False,True,False,True
5,False,True,True,False,True,False,False,False
6,True,True,False,False,False,True,False,False
7,True,False,False,False,False,True,False,True

In [3]:
# The below code takes the one hot encoded data and calculates the support for each item. 
# This is done by the apriori function. You can set a threshold and filter items that are below the threshold.

frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)

frequent_itemsets

    support                   itemsets
0     0.375                   (apples)
1     0.750                  (bananas)
2     0.375                    (bread)
3     0.625           (vanilla wafers)
4     0.500                   (yogurt)
5     0.250          (bananas, apples)
6     0.250   (apples, vanilla wafers)
7     0.250           (apples, yogurt)
8     0.250           (bananas, bread)
9     0.375  (bananas, vanilla wafers)
10    0.250          (bananas, yogurt)
11    0.250            (yogurt, bread)
12    0.250   (vanilla wafers, yogurt)

In [4]:
# The next step is to form the association rules. Based on some predefined criteria , 
# the association rules can be set. Here we are getting all the rule based on minimum confidence score of 0.5 .

association_rules(frequent_itemsets, metric="confidence", min_threshold=0.5)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(apples),(bananas),0.375,0.750,0.250,0.666667,0.888889,-0.031250,0.750
1,(apples),(vanilla wafers),0.375,0.625,0.250,0.666667,1.066667,0.015625,1.125
2,(apples),(yogurt),0.375,0.500,0.250,0.666667,1.333333,0.062500,1.500
3,(yogurt),(apples),0.500,0.375,0.250,0.500000,1.333333,0.062500,1.250
4,(bread),(bananas),0.375,0.750,0.250,0.666667,0.888889,-0.031250,0.750
5,(bananas),(vanilla wafers),0.750,0.625,0.375,0.500000,0.800000,-0.093750,0.750
6,(vanilla wafers),(bananas),0.625,0.750,0.375,0.600000,0.800000,-0.093750,0.625
7,(yogurt),(bananas),0.500,0.750,0.250,0.500000,0.666667,-0.125000,0.500
8,(yogurt),(bread),0.500,0.375,0.250,0.500000,1.333333,0.062500,1.250
9,(bread),(yogurt),0.375,0.500,0.250,0.666667,1.333333,0.062500,1.500
10,(yogurt),(vanilla wafers),0.500,0.625,0.250,0.500000,0.800000,-0.062500,0.750

In [5]:
# The association rules can also be filtered based on lift . The below code shows how it is done.

rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.2)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(apples),(yogurt),0.375,0.500,0.25,0.666667,1.333333,0.0625,1.50
1,(yogurt),(apples),0.500,0.375,0.25,0.500000,1.333333,0.0625,1.25
2,(yogurt),(bread),0.500,0.375,0.25,0.500000,1.333333,0.0625,1.25
3,(bread),(yogurt),0.375,0.500,0.25,0.666667,1.333333,0.0625,1.50

In [6]:
# Writing Custom Functions
# So far you have learnt how to filter the association rule based on some metrics and 
# threshold values. Other custom functions can also be applied to the rules. In the below code
# , the length of the antecedent is taken to and added as an additional column to the data frame. This can be used further for filtering.

rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
0,(apples),(yogurt),0.375,0.500,0.25,0.666667,1.333333,0.0625,1.50,1
1,(yogurt),(apples),0.500,0.375,0.25,0.500000,1.333333,0.0625,1.25,1
2,(yogurt),(bread),0.500,0.375,0.25,0.500000,1.333333,0.0625,1.25,1
3,(bread),(yogurt),0.375,0.500,0.25,0.666667,1.333333,0.0625,1.50,1

In [7]:
# Filtering Rules based on Subsets
# Once all the initial transformations are done , you can write a series of 
# criteria to filter the items . Below code explains one possible scenario.
# Here the length of the antecedant is greater than 2. The confidence score 
# is greater than or equal to 0.75 . The lift is greater than 1.2 .

rules[ (rules['antecedent_len'] >= 1) &
       (rules['confidence'] > 0.55) &
       (rules['lift'] > 1.2) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
0,(apples),(yogurt),0.375,0.5,0.25,0.666667,1.333333,0.0625,1.5,1
3,(bread),(yogurt),0.375,0.5,0.25,0.666667,1.333333,0.0625,1.5,1

# Apriori for association rule mining

Apriori Algorithm is a very efficient mechanism for generating Association Rules.

The main objective of this algorithm is to determine all the possible rules that satisfy the required support and confidence constraints.

**Steps - Singleton Set**

- First identify all possible single item steps
- Filter those items which do not satisfy the minimum support
- Retain only those items that satisfy the support and confidence threshold

**Steps - Doubleton Set**
- Find all two item sets
- Filter all items with minimum support
- Find all possible rules from this set
- Filter only those rules with minimum confidence
- Add rule to list of rules and move on

The steps mentioned above can be extended to multiple items and then determining all the possible rules that satisfy the constraints.

Finally it is advised to stop when the item set cannot be made any bigger.

CHALLENGES

Depending on the data collected, sometimes

- There can be too few item sets that satisfy the minimum support
- This might lead to missing out on strong associations because of lack of support

In [8]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.preprocessing import TransactionEncoder

import pandas as pd

dataset = [
    ['vanilla wafers', 'bananas' , 'dog food'],
    ['bananas', 'bread', 'yogurt'],
    ['bananas','apples','yogurt'],
    ['vanilla wafers','bananas','whipped cream'],
    ['bread', 'vanilla wafers' , 'yogurt'],
    ['milk' 'bread' 'bananas'],
    ['vanilla wafers', 'apples' , 'bananas'],
    ['yogurt', 'apples', 'vanilla wafers'],
    
]

In [9]:
# The below code explains how one hot encoding is done for the dataset and converted into a data frame.

oht = TransactionEncoder()
oht_ary = oht.fit(dataset).transform(dataset)
df = pd.DataFrame(oht_ary, columns=oht.columns_)

In [10]:
# The below code shows how the apriori function is called and the parameters 
# are passed to filter the items based on specific criteria.

frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)

In [11]:
association_rule = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)
print(association_rule)

  antecedents consequents  antecedent support  consequent support  support  \
0     (bread)    (yogurt)                0.25                 0.5     0.25

   confidence  lift  leverage  conviction
0         1.0   2.0     0.125         inf

# Frequent Pattern Mining

FP Growth starts with calculating the support for each item

The items are sorted based on their support value

Then the the items are reshuffled based on their support values

The next step is to create a graph

Each transaction is represented as a graph

Successive transactions are branched out of the initial graph

- Each transaction is identified
- The support for each item is calculated
- The transactions are sorted based on the support values of items contained in them

- Each transaction is taken and is represented as a tree
- The item with the highest support is the root node and the other nodes are formed in succession based on the support values
- The same process is repeated for other transactions
- The remaining transactions branch out from the first transaction


The FP Growth is one of the fastest algorithms

It is also very memory efficient


**Technique**

- Apriori

  - Here single items , pairs , triplets and other sequences are generated for the items across transactions


 - FP Growth

  - The sorted items are inserted based on the frequency into a pattern tree


**Runtime**  

- Apriori

  - Generating the candidate items is very time-consuming. The runtime of the algorithm increases exponentially, depending on the diversity of the items.


- FP Growth

   - The increase in runtime is linear and is dependent on the number of items and the transactions.

**Memory Usage**
   
 - Apriori

   - Saves different combination of the items.Consumes a lot of memory.


- FP Growth

  - A compact version of the database is stored. Memory consumption is less.

**Parallelizability**  


- Apriori

  - Generating the candidate items is parallelizable.


 - FP Growth

   - The data inherently is interdependent and every node is dependent on the root node.